services:
  backend:
    build: ./backend
    ports: 
      - '80:80'
    volumes:
      - /app/node_modules
      - ./backend:/app # bind mount
    env_file:
      - './env/backend.env'

  frontend:
    build: ./frontend
    ports: 
      - '5173:5173'
    volumes:
      - /app/node_modules
      - ./frontend:/app # bind mount


